FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    postgresql-client \
    bash \
    curl

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci

RUN npx prisma generate

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]