services:
  server:
    build: ./server
    container_name: tranquilo_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    environment:
    - NODE_ENV=production
    - PORT=5000
    - DATABASE_URL=postgresql://postgres.zelepeqoxbrqwzddlqbu:ACIen1.2021k@aws-0-us-east-2.pooler.supabase.com:5432/postgres?pgbouncer=true
    - JWT_SECRET=a8f5f167f44f4964e6c998dee827110c284f8c5e4d5c8b9e8f7c6d4a3b2e1f9e8d7c6b5a4f3e2d1c9b8a7f6e5d4c3b2a1
    - LOG_LEVEL=debug
    - LOG_FILE_PATH=./logs
    - FRONTEND_URL=https://tranquilo-hurghada.com
    - API_VERSION=v1
    - ACCESS_TOKEN_EXPIRY=15m
    - REFRESH_TOKEN_EXPIRY=7d
    - SALT_ROUNDS=10
    - ADMIN_EMAIL=admin@tranquilo-hughada.com
    - ADMIN_PASSWORD=Abcdef123
    - ADMIN_NAME=Tranquilo Hurghada
    - SMTP_PORT=587
    - SMTP_HOST=
    - SMTP_USER=reslab@aui.ma
    - SMTP_FROM=reslab@aui.ma
    - SMTP_PASS=Y!485280061358ol
    - PROD_URL=https://tranquilo-hurghada.com

  web:
    build: ./web
    container_name: tranquilo_web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - server