services:
  server:
    build: ./server
    container_name: tranquilo_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    environment:
    - NODE_ENV=production
  web:
    build: ./web
    container_name: tranquilo_web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - server