import type { Language } from "./types";

export const API_URL = import.meta.env.VITE_API_URL || '/api'
export const supportedLanguages = ['en', 'fr', 'ru', 'de'] as const;

export const languages: Language[] = [
    {
        code: 'en',
        name: 'English',
        nativeName: 'English',
        flag: '🇺🇸',
        rtl: false,
    },
    {
        code: 'fr',
        name: 'French',
        nativeName: 'Français',
        flag: '🇫🇷',
        rtl: false,
    },
    {
        code: 'ru',
        name: 'Russian',
        nativeName: 'Русский',
        flag: '🇷🇺',
        rtl: false,
    },
    {
        code: 'de',
        name: 'German',
        nativeName: 'Deutsch',
        flag: '🇩🇪',
        rtl: false,
    },
];

export const mottos = [
    'The Gateway to Your Hurghada Adventure',
    'From Desert Dunes to Coral Reefs—Start Here',
    'Your Red Sea Escape Awaits',
    'Paradise found in Hurghada',
];

export const colorMap = {
    PENDING: '#f59e0b',
    CONFIRMED: '#10b981',
    COMPLETED: '#059669',
    CANCELLED: '#6b7280',
    REJECTED: '#ef4444'
};

export const statusMap = {
    PENDING: 'Pending Approval',
    CONFIRMED: 'Confirmed',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    REJECTED: 'Rejected'
};

export const POPULAR_CITIES = [
    'Hurghada'
];



export const POPULAR_AMENITIES = [
    // Internet & Technology
    'wifi',
    'high_speed_internet',
    'smart_tv',
    'cable_tv',
    'netflix',
    'streaming_services',
    'gaming_console',
    'sound_system',
    'bluetooth_speaker',
    'computer_workspace',
    'printer',
    'charging_stations',
    'usb_outlets',

    // Kitchen & Dining
    'kitchen',
    'full_kitchen',
    'kitchenette',
    'microwave',
    'dishwasher',
    'refrigerator',
    'freezer',
    'oven',
    'stove',
    'toaster',
    'coffee_maker',
    'espresso_machine',
    'blender',
    'dining_table',
    'breakfast_bar',
    'outdoor_dining',
    'barbecue_grill',
    'bbq',
    'gas_grill',
    'charcoal_grill',

    // Laundry & Cleaning
    'washing_machine',
    'dryer',
    'washer_dryer',
    'iron',
    'ironing_board',
    'vacuum_cleaner',
    'cleaning_supplies',
    'laundry_service',

    // Climate Control
    'air_conditioning',
    'central_air',
    'heating',
    'central_heating',
    'fireplace',
    'electric_fireplace',
    'gas_fireplace',
    'wood_fireplace',
    'ceiling_fans',
    'portable_fans',
    'space_heater',

    // Outdoor Spaces
    'pool',
    'private_pool',
    'shared_pool',
    'indoor_pool',
    'heated_pool',
    'infinity_pool',
    'pool_heating',
    'hot_tub',
    'jacuzzi',
    'spa',
    'sauna',
    'steam_room',
    'balcony',
    'terrace',
    'patio',
    'deck',
    'rooftop_access',
    'garden',
    'private_garden',
    'courtyard',
    'outdoor_shower',
    'outdoor_kitchen',
    'fire_pit',
    'outdoor_fireplace',
    'gazebo',
    'pergola',
    'hammock',
    'outdoor_furniture',
    'sun_loungers',
    'beach_chairs',

    // Parking & Transportation
    'parking',
    'free_parking',
    'private_parking',
    'garage',
    'covered_parking',
    'street_parking',
    'valet_parking',
    'electric_car_charging',
    'bicycle_rental',
    'scooter_rental',
    'car_rental',
    'airport_shuttle',
    'public_transport_access',

    // Security & Safety
    'security_system',
    'security_cameras',
    'alarm_system',
    'safe_deposit_box',
    'smoke_detector',
    'carbon_monoxide_detector',
    'fire_extinguisher',
    'first_aid_kit',
    'security_guard',
    'gated_community',
    'keypad_entry',
    'smart_lock',

    // Entertainment & Recreation
    'tv',
    'flat_screen_tv',
    'projector',
    'home_theater',
    'board_games',
    'books',
    'library',
    'piano',
    'musical_instruments',
    'gym',
    'fitness_center',
    'exercise_equipment',
    'yoga_mats',
    'tennis_court',
    'basketball_court',
    'ping_pong_table',
    'pool_table',
    'foosball_table',
    'arcade_games',
    'dart_board',
    'children_playground',
    'swing_set',
    'trampoline',

    // Views & Location
    'ocean_view',
    'sea_view',
    'beach_view',
    'mountain_view',
    'city_view',
    'garden_view',
    'pool_view',
    'lake_view',
    'river_view',
    'forest_view',
    'countryside_view',
    'sunset_view',
    'sunrise_view',
    'panoramic_view',
    'waterfront',
    'beachfront',
    'beach_access',
    'private_beach',
    'direct_beach_access',
    'ski_in_ski_out',
    'golf_course_access',

    // Bedroom & Sleeping
    'master_bedroom',
    'en_suite_bathroom',
    'walk_in_closet',
    'king_size_bed',
    'queen_size_bed',
    'sofa_bed',
    'bunk_beds',
    'crib',
    'baby_cot',
    'extra_pillows',
    'luxury_linens',
    'blackout_curtains',
    'room_darkening_shades',
    'wake_up_service',

    // Bathroom & Personal Care
    'private_bathroom',
    'shared_bathroom',
    'bathtub',
    'jetted_tub',
    'walk_in_shower',
    'rainfall_shower',
    'bidet',
    'hair_dryer',
    'heated_towel_rails',
    'magnifying_mirror',
    'bathroom_essentials',
    'shampoo',
    'body_wash',
    'towels_provided',
    'robes',
    'slippers',

    // Accessibility
    'wheelchair_accessible',
    'elevator_access',
    'step_free_access',
    'accessible_bathroom',
    'grab_rails',
    'accessible_parking',
    'braille_signage',
    'hearing_accessible',
    'visual_aid_accessible',

    // Family & Children
    'family_friendly',
    'child_friendly',
    'high_chair',
    'baby_gate',
    'children_books_toys',
    'children_dinnerware',
    'baby_monitor',
    'changing_table',
    'baby_bath',
    'stroller',
    'car_seat',
    'babysitting_service',
    'children_pool',
    'shallow_end',

    // Pet Amenities
    'pet_friendly',
    'dog_friendly',
    'cat_friendly',
    'pet_bed',
    'pet_bowls',
    'pet_toys',
    'dog_park_nearby',
    'pet_sitting_service',
    'pet_grooming',
    'fenced_yard',

    // Business & Work
    'dedicated_workspace',
    'office_chair',
    'desk',
    'business_center',
    'meeting_room',
    'conference_facilities',
    'fax_machine',
    'scanner',
    'whiteboard',
    'projector_screen',

    // Luxury & Premium
    'luxury_amenities',
    'concierge_service',
    'butler_service',
    'maid_service',
    'daily_housekeeping',
    'room_service',
    'private_chef',
    'catering_service',
    'champagne_welcome',
    'welcome_basket',
    'fresh_flowers',
    'premium_toiletries',
    'marble_bathroom',
    'designer_furniture',
    'art_collection',
    'antique_furnishings',
    'wine_cellar',
    'wine_tasting',
    'private_bar',
    'mini_bar',
    'champagne_bar',

    // Health & Wellness
    'fitness_room',
    'personal_trainer',
    'massage_service',
    'spa_treatments',
    'meditation_space',
    'yoga_studio',
    'pilates_equipment',
    'wellness_programs',
    'detox_programs',
    'organic_garden',
    'healthy_meals',
    'nutritionist',

    // Services & Support
    '24_hour_checkin',
    'early_checkin',
    'late_checkout',
    'luggage_storage',
    'dry_cleaning',
    'grocery_delivery',
    'meal_delivery',
    'tour_booking',
    'ticket_booking',
    'translation_service',
    'local_guide',
    'travel_planning',
    'recommendation_service',

    // Unique Features
    'rooftop_terrace',
    'penthouse',
    'loft_style',
    'historic_building',
    'castle',
    'treehouse',
    'boat_house',
    'cave_dwelling',
    'glass_house',
    'eco_friendly',
    'solar_power',
    'sustainable_materials',
    'rainwater_harvesting',
    'organic_products',
    'locally_sourced',

    // Location Specific
    'ski_storage',
    'ski_equipment',
    'beach_equipment',
    'snorkeling_gear',
    'fishing_equipment',
    'hiking_gear',
    'bicycle_storage',
    'kayak_rental',
    'boat_rental',
    'jet_ski_rental',
    'golf_equipment',
    'tennis_equipment',

    // Seasonal & Weather
    'winter_amenities',
    'summer_amenities',
    'all_season',
    'weatherproof',
    'storm_shutters',
    'backup_generator',
    'power_backup',
    'water_backup',

    // Cultural & Educational
    'cultural_tours',
    'cooking_classes',
    'language_lessons',
    'art_workshops',
    'music_lessons',
    'dance_classes',
    'local_experiences',
    'cultural_immersion',
    'historical_tours',
    'nature_walks',
    'bird_watching',
    'stargazing',

    // Special Occasions
    'wedding_venue',
    'event_hosting',
    'party_venue',
    'romantic_setting',
    'honeymoon_suite',
    'anniversary_package',
    'birthday_celebrations',
    'corporate_events',
    'team_building',
    'retreat_venue'
];